---
- name: ...
  hosts: nxos1
  gather_facts: no
  vars_files:
    - pass.yml
  tasks:
    - name: ...
      nxos_config:
        lines:
          - feature ospf
          - feature vn-segment-vlan-based
          - feature nv overlay 
#          - system jumbotu 9216

    - name: config ospf
      nxos_config:
        lines:
          - router ospf 1
    - name: set ospf
      nxos_config:
        parents:
          - int e1/2
        lines:
          - no switchport
          - ip add 100.1.1.1/30
          - ip router ospf 1 area 0
    - name: create vlan 50
      nxos_config:
        parents:
          - vlan 50
        lines:
          - vn-segment 5000
    - name: access vlan 50
      nxos_config:
        parents:
          - int e1/3
        lines:
          - switchport
          - switchport mode access
          - switchport access vlan 50
    - name: ...
      nxos_config:
        parents:
          - int nve 1
        lines:
          - no shut 
          - source-interface loopback 0 
          - member vni 5000
          - ingress-replication protocol static
          - peer-ip 20.20.20.20
    - name: ...
      nxos_config:
        parents:
          - int loopback 0
        lines:
          - ip add 10.10.10.10/32